/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package capstone;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.text.*;
import java.applet.*;
import static java.lang.System.out;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;



/**
 *
 * @author Shane
 */
public class Admins extends javax.swing.JFrame {

    /**
     
     */
    public Admins() {
         DbConnector.createDatabase();
        DbConnector.createTables();
        initComponents();
        
        groupButton();
        
        

        setVisibleIfAdmin();
        /*
         JComboBox cb = new JComboBox();
         cb.addActionListener(new ActionListener(){
              public void actionPerformed(ActionEvent event) {
                  
              JComboBox cb = (JComboBox) event.getSource();
                Object selected = cb.getSelectedItem();
                if(selected.toString().equals("item1"))
                field.getText("30");
                else if(selected.toString().equals("item2"))
                    field.setText("40");
              }
         });
         * */
              
    };

    /**
     * sets add player add team edit player and delete player visible if Admin
     */
    public void setVisibleIfAdmin() {
        if (Capstone.IS_ADMIN == true) {
            btnAddPlayer.setVisible(true);
            btnAddTeam.setVisible(true);
            btnEditPlayer.setVisible(true);
            btnDelete.setVisible(true);
        } else {
           btnAddPlayer.setVisible(false);
           btnAddTeam.setVisible(false);
           btnEditPlayer.setVisible(false);
           btnDelete.setVisible(false);
        }
    }
    /**
     * creates a button group of radio buttons
     */
    
     private void groupButton( ) {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(radFindPlayer);
        bg1.add(radFindTeam);
        bg1.add(radPosition);

}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radFindPlayer = new javax.swing.JRadioButton();
        radFindTeam = new javax.swing.JRadioButton();
        radPosition = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        btnAddPlayer = new javax.swing.JButton();
        btnEditPlayer = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAddTeam = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fantasy Hockey Projector");

        radFindPlayer.setText("Find Player");
        radFindPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFindPlayerActionPerformed(evt);
            }
        });

        radFindTeam.setText("Find Team");
        radFindTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFindTeamActionPerformed(evt);
            }
        });

        radPosition.setText("Search By Position");
        radPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPositionActionPerformed(evt);
            }
        });

        btnLogin.setText("Admin Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnAddPlayer.setText("Add Player");
        btnAddPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPlayerMouseClicked(evt);
            }
        });
        btnAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlayerActionPerformed(evt);
            }
        });

        btnEditPlayer.setText("Edit Player");

        btnDelete.setText("Delete");

        btnAddTeam.setText("Add Team");
        btnAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeamActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jButton2.setText("View Stats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radPosition)
                                    .addComponent(radFindTeam)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radFindPlayer)
                                        .addGap(64, 64, 64)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnAddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddTeam)
                                .addGap(21, 21, 21)
                                .addComponent(btnEditPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogin))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radFindPlayer)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addComponent(radFindTeam)
                .addGap(30, 30, 30)
                .addComponent(radPosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlayer)
                    .addComponent(btnEditPlayer)
                    .addComponent(btnDelete)
                    .addComponent(btnAddTeam)
                    .addComponent(btnClose))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /* to add a player 
         * 
         */
    private void btnAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlayerActionPerformed
        addPlayerDialog input1 = new addPlayerDialog(this, true);
        
        input1.setVisible(true);
        
    
       

    }//GEN-LAST:event_btnAddPlayerActionPerformed
      /* button to add a player brings up addPlayerDialog
         * 
         */
    private void btnAddPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPlayerMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddPlayerMouseClicked
      /* radio button to select a player
         * 
         */
    private void radFindPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFindPlayerActionPerformed
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
        jComboBox1.addItem("CHOOSE PLAYER");
        for (int i = 0; i < DbConnector.getAllPlayers().size(); i++)
             jComboBox1.addItem(DbConnector.getAllPlayers().get(i));
    }//GEN-LAST:event_radFindPlayerActionPerformed
    
         /* button to add a player brings up AddTeamDialog 
         * 
         */
    
    private void btnAddTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeamActionPerformed
        // TODO add your handling code here:
        AddTeamDialog input1 = new AddTeamDialog(this, true);
        
        input1.setVisible(true);
    }//GEN-LAST:event_btnAddTeamActionPerformed
      /* button to login as Admin 
         * 
         */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //AdminLoginDialog input1 = new AdminLoginDialog(this, true);
        
        //input1.setVisible(true);
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a password:");
        JPasswordField pass = new JPasswordField(10){
            public void addNotify(){
                super.addNotify();
                requestFocusInWindow();
            }
        };
        
        panel.add(label);
        panel.add(pass);
        
        String[] options = new String[]{"Login", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Enter Password",
                         JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                         null, options, options[0]);
        
        if(option == 0) // pressing OK button
        {
             String password = new String(pass.getPassword());
             System.out.println("The password entered was: " + password);
             try {
                Capstone.IS_ADMIN = DbConnector.checkPassword("shane", password);
                setVisibleIfAdmin();
             } catch (Exception ex) {
                Capstone.IS_ADMIN = false;
                System.out.println("FATAL ERROR: " + ex);
                JOptionPane.showMessageDialog(null, "Error: Incorrect login credentials. Please try again! (Or server is not turned on)", "Bad Login:", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed
      /* button to close
         * 
         */
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed
  /* radio button to select a team
         * 
         */
    private void radFindTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFindTeamActionPerformed
        jComboBox1.removeAllItems();
        jComboBox1.addItem("CHOOSE TEAM");
        for (int i = 0; i < DbConnector.getAllTeams().size(); i++)
            jComboBox1.addItem(DbConnector.getAllTeams().get(i));
    }//GEN-LAST:event_radFindTeamActionPerformed

        /* radio button to select a postiion
         * 
         */
    private void radPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPositionActionPerformed
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
        jComboBox1.addItem("CHOOSE POSITION");
        for (int i = 0; i < DbConnector.getAllPositions().size(); i++)
            jComboBox1.addItem(DbConnector.getAllPositions().get(i));
    }//GEN-LAST:event_radPositionActionPerformed

     /**
     * when button is pressed shows the ResultDialg table of selected item from the combo box
      */
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<String> players = new ArrayList(0);
        if (radFindPlayer.isSelected()) {
            String name = (jComboBox1.getSelectedItem()).toString();
            players.add(0,name);
        }
        else if (radFindTeam.isSelected()) {    
            String name = (jComboBox1.getSelectedItem()).toString();
            int team_id =  DbConnector.getTeamID(name);
            players = DbConnector.getPlayersbyTeam(team_id);
        }
        else {
             String name = (jComboBox1.getSelectedItem()).toString();
            int position_id =  DbConnector.getPositionID(name);
            players = DbConnector.getPlayersbyPosition(position_id);
        }
            ResultDialog input1 = new ResultDialog(this, true);
        input1.updateTable(players);
        input1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admins().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlayer;
    private javax.swing.JButton btnAddTeam;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditPlayer;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton2;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radFindPlayer;
    private javax.swing.JRadioButton radFindTeam;
    private javax.swing.JRadioButton radPosition;
    // End of variables declaration//GEN-END:variables
}
